CreateClientConVar("zs_damagefloatersstyle", "0", true, false)
CreateClientConVar("zs_classichud", "0", true, false)

hook.Add("AddExtraOptions", "AddExtraOptions.Life", function(panellist, optionsmenu)
	local DButton = vgui.Create( "DButton" )
	DButton:SetFont("ZSHUDFontSmaller")
	DButton:SetText( "TPF: Options" )
	DButton:SetTall(32)
	DButton:DockMargin(0, 0, 0, 12)
	DButton:DockPadding(0, 12, 0, 12)
	DButton.DoClick = function()
		LocalPlayer():ConCommand( "tpf_open_menu" )
	end
	panellist:AddItem(DButton)

	local check = vgui.Create("DCheckBoxLabel", optionsmenu)
	check:SetText("Gmod Legs: Enabled")
	check:SetConVar("cl_legs")
	check:SizeToContents()
	panellist:AddItem(check)
	
	local check = vgui.Create("DCheckBoxLabel", optionsmenu)
	check:SetText("Gmod Legs: First-Person Death")
	check:SetConVar("cl_deathview")
	check:SizeToContents()
	panellist:AddItem(check)
	
	local check = vgui.Create("DCheckBoxLabel", optionsmenu)
	check:SetText("Atmos: Hud Effects")
	check:SetConVar("atmos_cl_hudeffects")
	check:SizeToContents()
	panellist:AddItem(check)
	
	local check = vgui.Create("DCheckBoxLabel", optionsmenu)
	check:SetText("Atmos: Weather")
	check:SetConVar("atmos_cl_weather")
	check:SizeToContents()
	panellist:AddItem(check)
	
	local check = vgui.Create("DCheckBoxLabel", optionsmenu)
	check:SetText("Atmos: Rain Splashes")
	check:SetConVar("atmos_cl_rainsplash")
	check:SizeToContents()
	panellist:AddItem(check)
	
	local slider = vgui.Create("DNumSlider", optionsmenu)
	slider:SetDecimals(0)
	slider:SetMinMax(16, 64)
	slider:SetConVar("atmos_cl_rainperparticle")
	slider:SetText("Atmos: Max Rain Particles")
	slider:SizeToContents()
	panellist:AddItem(slider)
	
	local slider = vgui.Create("DNumSlider", optionsmenu)
	slider:SetDecimals(0)
	slider:SetMinMax(16, 32)
	slider:SetConVar("atmos_cl_rainradius")
	slider:SetText("Atmos: Max Rain Radius")
	slider:SizeToContents()
	panellist:AddItem(slider)
	
	local check = vgui.Create("DCheckBoxLabel", optionsmenu)
	check:SetText("Enable Classic HUD")
	check:SetConVar("zs_classichud")
	check:SizeToContents()
	panellist:AddItem(check)
	
	panellist:AddItem(EasyLabel(optionsmenu, "Damage Indicator Style", "DefaultFontSmall", color_white))
	local dropdown = vgui.Create("DComboBox", optionsmenu)
	dropdown:SetMouseInputEnabled(true)
	dropdown:AddChoice("Classic")
	dropdown:AddChoice("New")
	dropdown.OnSelect = function(me, index, value, data)
		RunConsoleCommand("zs_damagefloatersstyle", value == "Classic" and 1 or 0)
	end
	dropdown:SetText(GetConVarNumber("zs_damagefloatersstyle") == 1 and "Classic" or "New")
	panellist:AddItem(dropdown)
end)