if (SERVER) then
	AddCSLuaFile( "sh_playermodels.lua" )
	player_manager.AddValidModel( "Arctic", "models/DPFilms/Metropolice/Playermodels/pm_arctic_police.mdl" )
	player_manager.AddValidModel( "Badass", "models/DPFilms/Metropolice/Playermodels/pm_badass_police.mdl" )
	player_manager.AddValidModel( "SpecOps", "models/DPFilms/Metropolice/Playermodels/pm_biopolice.mdl" )
	player_manager.AddValidModel( "City 08 Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_c08cop.mdl" )
	player_manager.AddValidModel( "Civil Medic", "models/DPFilms/Metropolice/Playermodels/pm_civil_medic.mdl" )
	player_manager.AddValidModel( "Black Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_black_police.mdl" )
	player_manager.AddValidModel( "Skull Squad", "models/DPFilms/Metropolice/Playermodels/pm_skull_police.mdl" )
	player_manager.AddValidModel( "Beta Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_hl2beta_police.mdl" )
	player_manager.AddValidModel( "Blue eyed Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_hl2concept.mdl" )
	player_manager.AddValidModel( "HD Barney", "models/DPFilms/Metropolice/Playermodels/pm_HD_Barney.mdl" )
	player_manager.AddValidModel( "HD Barney EP1", "models/DPFilms/Metropolice/Playermodels/pm_HD_Barney_ep1.mdl" )
	player_manager.AddValidModel( "HD Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_HDpolice.mdl" )
	player_manager.AddValidModel( "Hunter Squad", "models/DPFilms/Metropolice/Playermodels/pm_hunter_police.mdl" )
	player_manager.AddValidModel( "Phoenix Squad", "models/DPFilms/Metropolice/Playermodels/pm_phoenix_police.mdl" )
	player_manager.AddValidModel( "Breen Troops", "models/DPFilms/Metropolice/Playermodels/pm_police_bt.mdl" )
	player_manager.AddValidModel( "Elite Shock Unit", "models/DPFilms/Metropolice/Playermodels/pm_elite_police.mdl" )
	player_manager.AddValidModel( "RTB Trenchcoat", "models/DPFilms/Metropolice/Playermodels/pm_rtb_police.mdl" )
	player_manager.AddValidModel( "Female Police", "models/DPFilms/Metropolice/Playermodels/pm_female_police.mdl" )
	player_manager.AddValidModel( "Fragger Police", "models/DPFilms/Metropolice/Playermodels/pm_police_fragger.mdl" )
	player_manager.AddValidModel( "Trenchcoat Police", "models/DPFilms/Metropolice/Playermodels/pm_policetrench.mdl" )
	player_manager.AddValidModel( "Rogue", "models/DPFilms/Metropolice/Playermodels/pm_rogue_police.mdl" )
	player_manager.AddValidModel( "Resistance Police", "models/DPFilms/Metropolice/Playermodels/pm_resistance_police.mdl" )
	player_manager.AddValidModel( "Retrocop", "models/DPFilms/Metropolice/Playermodels/pm_retrocop.mdl" )
	player_manager.AddValidModel( "Steampunk Police", "models/DPFilms/Metropolice/Playermodels/pm_steampunk_police.mdl" )
	player_manager.AddValidModel( "TF2 RED Police", "models/DPFilms/Metropolice/Playermodels/pm_tf2_metrocop_red.mdl" )
	player_manager.AddValidModel( "TF2 BLU Police", "models/DPFilms/Metropolice/Playermodels/pm_tf2_metrocop_blu.mdl" )
	player_manager.AddValidModel( "Tribal", "models/DPFilms/Metropolice/Playermodels/pm_tribal_police.mdl" )
	player_manager.AddValidModel( "Tron Police", "models/DPFilms/Metropolice/Playermodels/pm_tron_police_cn.mdl" )
	player_manager.AddValidModel( "Tron Police Orange", "models/DPFilms/Metropolice/Playermodels/pm_tron_police_or.mdl" )
	player_manager.AddValidModel( "Urban Camo", "models/DPFilms/Metropolice/Playermodels/pm_urban_police.mdl" )
	player_manager.AddValidModel( "Zombie Police", "models/DPFilms/Metropolice/Playermodels/pm_zombie_police.mdl" )
	player_manager.AddValidModel( "CSGO: GSG9", "models/player/enhancedgsg9.mdl" )
	player_manager.AddValidModel( "CSGO: Phoenix", "models/player/enhancedphoenix.mdl" )
	player_manager.AddValidModel( "BF4_US_01", "models/steinman/bf4/us_01.mdl" )
	player_manager.AddValidModel( "BF4_US_02", "models/steinman/bf4/us_02.mdl" )
	player_manager.AddValidModel( "BF4_US_03", "models/steinman/bf4/us_03.mdl" )
	player_manager.AddValidModel( "BF4_US_04", "models/steinman/bf4/us_04.mdl" )
	player_manager.AddValidModel( "BF4_RU_01", "models/steinman/bf4/ru_01.mdl" )
	player_manager.AddValidModel( "BF4_RU_02", "models/steinman/bf4/ru_02.mdl" )
	player_manager.AddValidModel( "BF4_RU_03", "models/steinman/bf4/ru_03.mdl" )
	player_manager.AddValidModel( "BF4_RU_04", "models/steinman/bf4/ru_04.mdl" )
	player_manager.AddValidModel( "Eli Black Mesa", "models/player/blackmesa_eli.mdl" )
	player_manager.AddValidModel( "Hev Black Mesa", "models/player/blackmesa_hev.mdl" )
	player_manager.AddValidModel( "Kleiner Black Mesa", "models/player/blackmesa_kleiner.mdl" )
	player_manager.AddValidModel( "Guard Black Mesa", "models/player/blackmesa_guard.mdl" )
	player_manager.AddValidModel( "Marine Black Mesa", "models/player/blackmesa_marine.mdl" )
	player_manager.AddValidModel( "Scientific Black Mesa", "models/player/blackmesa_scientific.mdl" )
	player_manager.AddValidModel( "Scientific Female Black Mesa", "models/player/blackmesa_scientific_female.mdl" )
	player_manager.AddValidModel( "Death Stroke", "models/norpo/ArkhamOrigins/Assassins/Deathstroke_ValveBiped.mdl" )
	player_manager.AddValidModel( "Daryl Dixon", "models/The Walking Dead Survival Instincts/Daryl_Dixon.mdl" )
	player_manager.AddValidModel( "Merle Dixon", "models/The Walking Dead Survival Instincts/Merle_Dixon.mdl" )
	player_manager.AddValidModel( "EDFSoldier", "models/jessev92/player/misc/edfsoldier.mdl" )
	player_manager.AddValidModel( "MrFoster Classic", "models/mark2580/killing/mr_foster_classic.mdl" )
	player_manager.AddValidModel( "MrsFoster Classic", "models/mark2580/killing/mrs_foster_classic.mdl" )
	player_manager.AddValidModel( "MrFoster", "models/mark2580/killing/steampunk/sp_mr_foster.mdl" )
	player_manager.AddValidModel( "MrsFoster", "models/mark2580/killing/steampunk/sp_mrs_foster.mdl" )
	player_manager.AddValidModel( "Gordon Freeman", "models/Inaki/Characters/gordon_freeman.mdl" )
	player_manager.AddValidModel( "ODST", "models/voxelzero/player/odst.mdl" )
	player_manager.AddValidModel( "Atlas", "models/survivors/atlas.mdl" )
	player_manager.AddValidModel( "HUNK_cvp", "models/player/lordvipes/rerc_hunk/hunk_cvp_fix.mdl" )
	player_manager.AddValidModel( "NIGHT HAWK_cvp", "models/player/lordvipes/rerc_nighthawk/nighthawk_cvp_fix.mdl" )
	player_manager.AddValidModel( "Clone Commando", "models/player/SGG/Starwars/clone_commando.mdl" )
	player_manager.AddValidModel( "Clone Commando (MP A)", "models/Player/SGG/Starwars/clone_commando_mp_a.mdl" )
	player_manager.AddValidModel( "Clone Commando (MP B)", "models/Player/SGG/Starwars/clone_commando_mp_b.mdl" )
	player_manager.AddValidModel( "Clone Commando (MP C)", "models/Player/SGG/Starwars/clone_commando_mp_c.mdl" )
	player_manager.AddValidModel( "Clone Commando (MP D)", "models/Player/SGG/Starwars/clone_commando_mp_d.mdl" )
	player_manager.AddValidModel( "Clone Commando Boss", "models/Player/SGG/Starwars/clone_commando_38.mdl" )
	player_manager.AddValidModel( "Clone Commando Fixer", "models/Player/SGG/Starwars/clone_commando_40.mdl" )
	player_manager.AddValidModel( "Clone Commando Scorch", "models/player/sgg/starwars/clone_commando_62_fix.mdl" )
	player_manager.AddValidModel( "Clone Commando Sev", "models/Player/SGG/Starwars/clone_commando_07.mdl" )
	player_manager.AddValidModel( "Bill", "models/enhanced_survivors/player/player_namvet.mdl" )
	player_manager.AddValidModel( "Thresh", "models/thresh/thresh_fix.mdl")
	player_manager.AddValidModel( "Tron Anon", "models/player/anon/anon.mdl" )
	player_manager.AddValidModel( "Marine", "models/voxelzero/player/marine.mdl" )
	player_manager.AddValidModel( "Lizardman Chiulin", "models/lizards/lizardmanvd.mdl" )
	player_manager.AddValidModel( "Lizardman Ekinar", "models/lizards/lizardmanekinar.mdl" )
	player_manager.AddValidModel( "Lizardman Garway", "models/lizards/lizardmangarway.mdl" )
	player_manager.AddValidModel( "Lizardman Kazgulam", "models/lizards/lizardmankazgulam.mdl" )
	player_manager.AddValidModel( "Lizardman Keser", "models/lizards/lizardmankeser.mdl" )
	player_manager.AddValidModel( "Lizardman Shaman", "models/lizards/lizardmanshaman.mdl" )
	player_manager.AddValidModel( "Lizardman Verafim", "models/lizards/lizardmanverafim.mdl" )
	player_manager.AddValidModel( "Lizardman Warrior", "models/lizards/lizardmanwarrior.mdl" )
	player_manager.AddValidModel( "Lizardman Shark", "models/lizards/lizardmanshark.mdl" )
	player_manager.AddValidModel( "Inferno Armour", "models/Mass Effect 2/player/inferno_armour.mdl")
	player_manager.AddValidModel( "Inferno Armour Colour", "models/Mass Effect 2/player/inferno_armour_colour.mdl")
	player_manager.AddValidModel( "halo3elite", "Models/player/halo3elite.mdl" )
	player_manager.AddValidModel( "Spartan (Halo 3 MP)", "models/player/lordvipes/h3_spartans_mps/h3spartan_mps_cvp.mdl" )
	player_manager.AddValidModel( "Haus: The Plague Doktor", "models/Splinks/plague_doktor/Plague_Doktor.mdl" )
	player_manager.AddValidModel( "Iron Man", "models/Avengers/Iron Man/mark7_player.mdl" )
	player_manager.AddValidModel( "Iron Patriot", "models/Avengers/Iron Man/patriot_player.mdl" )
end

player_manager.AddValidHands( "Arctic", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Badass", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "SpecOps", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "City 08 Metro Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Civil Medic", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Black Metro Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Skull Squad", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Beta Metro Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Blue eyed Metro Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "HD Barney", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "HD Barney EP1", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "HD Metro Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Hunter Squad", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Phoenix Squad", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Breen Troops", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Elite Shock Unit", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "RTB Trenchcoat", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Female Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Fragger Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Trenchcoat Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Rogue", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Resistance Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Retrocop", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Steampunk Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "TF2 RED Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "TF2 BLU Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Tribal", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Tron Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Tron Police Orange", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Urban Camo", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "Zombie Police", "models/weapons/c_arms_metropolice.mdl", 0, "00000000" )
player_manager.AddValidHands( "CSGO: GSG9", "models/weapons/c_arms_gsg9.mdl", 0, "00000000" )
player_manager.AddValidHands( "CSGO: Phoenix", "models/weapons/c_arms_phoenix.mdl", 0, "00000000" )
player_manager.AddValidHands( "BF4_US_01", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "BF4_US_02", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "BF4_US_03", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "BF4_US_04", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "BF4_RU_01", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "BF4_RU_02", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "BF4_RU_03", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "BF4_RU_04", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "Death Stroke", "models/weapons/c_arms_deathstroke.mdl", 0, "00000000" )
player_manager.AddValidHands( "Merle Dixon", "models/weapons/c_arms_merle_dixon.mdl", 0, "00000000" )
player_manager.AddValidHands( "EDFSoldier", "models/weapons/c_arms_combine.mdl", 0, "00000000" )
player_manager.AddValidHands( "MrFoster Classic", "models/weapons/c_arms_mr_foster_classic.mdl", 0, "00000000" )
player_manager.AddValidHands( "MrsFoster Classic", "models/weapons/c_arms_mrs_foster_classic.mdl", 0, "00000000" )
player_manager.AddValidHands( "MrFoster", "models/weapons/c_arms_sp_mr_foster.mdl", 0, "00000000" )
player_manager.AddValidHands( "MrsFoster", "models/weapons/c_arms_sp_mrs_foster.mdl", 1, "00000000" )
player_manager.AddValidHands( "Gordon Freeman", "models/weapons/c_arms_hev.mdl", 0, "00000000" )
player_manager.AddValidHands( "ODST", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "Atlas", "models/weapons/c_arms_atlas.mdl", 0, "00000000" )
player_manager.AddValidHands( "HUNK_cvp", "models/weapons/c_arms_hunk.mdl", 0, "00000000" )
player_manager.AddValidHands( "NIGHT HAWK_cvp", "models/weapons/c_arms_nighthawk.mdl", 0, "00000000" )
player_manager.AddValidHands( "Bill", "models/weapons/c_arms_namvet.mdl", 0, "00000000" )
player_manager.AddValidHands( "Thresh", "models/weapons/c_arms_thresh.mdl", 0, "00000000" )
player_manager.AddValidHands( "Tron Anon", "models/weapons/c_arms_anon.mdl", 0, "00000000" )
player_manager.AddValidHands( "Marine", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Chiulin", "models/weapons/c_arms_lizardman.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Ekinar", "models/weapons/c_arms_lizardman_ekinar.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Garway", "models/weapons/c_arms_lizardman_garway.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Kazgulam", "models/weapons/c_arms_lizardman_kazgulam.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Keser", "models/weapons/c_arms_lizardman_keser.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Shaman", "models/weapons/c_arms_lizardman_shaman.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Verafim", "models/weapons/c_arms_lizardman_verafim.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Warrior", "models/weapons/c_arms_lizardman_warrior.mdl", 0, "00000000" )
player_manager.AddValidHands( "Lizardman Shark", "models/weapons/c_arms_lizardman_shark.mdl", 0, "00000000" )
player_manager.AddValidHands( "halo3elite", "models/weapons/c_arms_elite.mdl", 0, "00000000" )
player_manager.AddValidHands( "Spartan (Halo 3 MP)", "models/weapons/c_arms_spartan.mdl", 0, "00000000" )
player_manager.AddValidHands( "Haus: The Plague Doktor", "models/weapons/c_arms_plague_doktor.mdl", 0, "00000000" )
player_manager.AddValidHands( "Iron Man", "models/Avengers/Iron Man/c_arms_mark7.mdl", 0, "00000000" )
player_manager.AddValidHands( "Iron Patriot", "models/Avengers/Iron Man/c_arms_patriot.mdl", 0, "00000000" )

list.Set( "PlayerOptionsModel", "Arctic", "models/DPFilms/Metropolice/Playermodels/pm_arctic_police.mdl" )
list.Set( "PlayerOptionsModel", "Badass", "models/DPFilms/Metropolice/Playermodels/pm_badass_police.mdl" )
list.Set( "PlayerOptionsModel", "SpecOps", "models/DPFilms/Metropolice/Playermodels/pm_biopolice.mdl" )
list.Set( "PlayerOptionsModel", "City 08 Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_c08cop.mdl" )
list.Set( "PlayerOptionsModel", "Civil Medic", "models/DPFilms/Metropolice/Playermodels/pm_civil_medic.mdl" )
list.Set( "PlayerOptionsModel", "Black Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_black_police.mdl" )
list.Set( "PlayerOptionsModel", "Skull Squad", "models/DPFilms/Metropolice/Playermodels/pm_skull_police.mdl" )
list.Set( "PlayerOptionsModel", "Beta Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_hl2beta_police.mdl" )
list.Set( "PlayerOptionsModel", "Blue eyed Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_hl2concept.mdl" )
list.Set( "PlayerOptionsModel", "HD Barney", "models/DPFilms/Metropolice/Playermodels/pm_HD_Barney.mdl" )
list.Set( "PlayerOptionsModel", "HD Barney EP1", "models/DPFilms/Metropolice/Playermodels/pm_HD_Barney_ep1.mdl" )
list.Set( "PlayerOptionsModel", "HD Metro Police", "models/DPFilms/Metropolice/Playermodels/pm_HDpolice.mdl" )
list.Set( "PlayerOptionsModel", "Hunter Squad", "models/DPFilms/Metropolice/Playermodels/pm_hunter_police.mdl" )
list.Set( "PlayerOptionsModel", "Phoenix Squad", "models/DPFilms/Metropolice/Playermodels/pm_phoenix_police.mdl" )
list.Set( "PlayerOptionsModel", "Breen Troops", "models/DPFilms/Metropolice/Playermodels/pm_police_bt.mdl" )
list.Set( "PlayerOptionsModel", "Breen Troops", "models/DPFilms/Metropolice/Playermodels/pm_police_bt.mdl" )
list.Set( "PlayerOptionsModel", "Elite Shock Unit", "models/DPFilms/Metropolice/Playermodels/pm_elite_police.mdl" )
list.Set( "PlayerOptionsModel", "RTB Trenchcoat", "models/DPFilms/Metropolice/Playermodels/pm_rtb_police.mdl" )
list.Set( "PlayerOptionsModel", "Female Police", "models/DPFilms/Metropolice/Playermodels/pm_female_police.mdl" )
list.Set( "PlayerOptionsModel", "Fragger Police", "models/DPFilms/Metropolice/Playermodels/pm_police_fragger.mdl" )
list.Set( "PlayerOptionsModel", "Trenchcoat Police", "models/DPFilms/Metropolice/Playermodels/pm_policetrench.mdl" )
list.Set( "PlayerOptionsModel", "Rogue", "models/DPFilms/Metropolice/Playermodels/pm_rogue_police.mdl" )
list.Set( "PlayerOptionsModel", "Resistance Police", "models/DPFilms/Metropolice/Playermodels/pm_resistance_police.mdl" )
list.Set( "PlayerOptionsModel", "Retrocop", "models/DPFilms/Metropolice/Playermodels/pm_retrocop.mdl" )
list.Set( "PlayerOptionsModel", "Steampunk Police", "models/DPFilms/Metropolice/Playermodels/pm_steampunk_police.mdl" )
list.Set( "PlayerOptionsModel", "TF2 RED Police", "models/DPFilms/Metropolice/Playermodels/pm_tf2_metrocop_red.mdl" )
list.Set( "PlayerOptionsModel", "TF2 BLU Police", "models/DPFilms/Metropolice/Playermodels/pm_tf2_metrocop_blu.mdl" )
list.Set( "PlayerOptionsModel", "Tribal", "models/DPFilms/Metropolice/Playermodels/pm_tribal_police.mdl" )
list.Set( "PlayerOptionsModel", "Tron Police", "models/DPFilms/Metropolice/Playermodels/pm_tron_police_cn.mdl" )
list.Set( "PlayerOptionsModel", "Tron Police Orange", "models/DPFilms/Metropolice/Playermodels/pm_tron_police_or.mdl" )
list.Set( "PlayerOptionsModel", "Urban Camo", "models/DPFilms/Metropolice/Playermodels/pm_urban_police.mdl" )
list.Set( "PlayerOptionsModel", "Zombie Police", "models/DPFilms/Metropolice/Playermodels/pm_zombie_police.mdl" )
list.Set( "PlayerOptionsModel", "CSGO: GSG9", "models/player/enhancedgsg9.mdl" )
list.Set( "PlayerOptionsModel", "CSGO: Phoenix", "models/player/enhancedphoenix.mdl" )
list.Set( "PlayerOptionsModel", "BF4_US_01", "models/steinman/bf4/us_01.mdl" )
list.Set( "PlayerOptionsModel", "BF4_US_02", "models/steinman/bf4/us_02.mdl" )
list.Set( "PlayerOptionsModel", "BF4_US_03", "models/steinman/bf4/us_03.mdl" )
list.Set( "PlayerOptionsModel", "BF4_US_04", "models/steinman/bf4/us_04.mdl" )
list.Set( "PlayerOptionsModel", "BF4_RU_01", "models/steinman/bf4/ru_01.mdl" )
list.Set( "PlayerOptionsModel", "BF4_RU_02", "models/steinman/bf4/ru_02.mdl" )
list.Set( "PlayerOptionsModel", "BF4_RU_03", "models/steinman/bf4/ru_03.mdl" )
list.Set( "PlayerOptionsModel", "BF4_RU_04", "models/steinman/bf4/ru_04.mdl" )
list.Set( "PlayerOptionsModel", "Eli Black Mesa", "models/player/blackmesa_eli.mdl" )
list.Set( "PlayerOptionsModel", "Hev Black Mesa", "models/player/blackmesa_hev.mdl" )
list.Set( "PlayerOptionsModel", "Kleiner Black Mesa", "models/player/blackmesa_kleiner.mdl" )
list.Set( "PlayerOptionsModel", "Guard Black Mesa", "models/player/blackmesa_guard.mdl" )
list.Set( "PlayerOptionsModel", "Marine Black Mesa", "models/player/blackmesa_marine.mdl" )
list.Set( "PlayerOptionsModel", "Scientific Black Mesa", "models/player/blackmesa_scientific.mdl" )
list.Set( "PlayerOptionsModel", "Scientific Female Black Mesa", "models/player/blackmesa_scientific_female.mdl" )
list.Set( "PlayerOptionsModel", "Death Stroke", "models/norpo/ArkhamOrigins/Assassins/Deathstroke_ValveBiped.mdl" )
list.Set( "PlayerOptionsModel", "Daryl Dixon", "models/The Walking Dead Survival Instincts/Daryl_Dixon.mdl" )
list.Set( "PlayerOptionsModel", "Merle Dixon", "models/The Walking Dead Survival Instincts/Merle_Dixon.mdl" )
list.Set( "PlayerOptionsModel", "EDFSoldier", "models/jessev92/player/misc/edfsoldier.mdl" )
list.Set( "PlayerOptionsModel", "MrFoster Classic", "models/mark2580/killing/mr_foster_classic.mdl" )
list.Set( "PlayerOptionsModel", "MrsFoster Classic", "models/mark2580/killing/mrs_foster_classic.mdl" )
list.Set( "PlayerOptionsModel", "MrFoster", "models/mark2580/killing/steampunk/sp_mr_foster.mdl" )
list.Set( "PlayerOptionsModel", "MrsFoster", "models/mark2580/killing/steampunk/sp_mrs_foster.mdl" )
list.Set( "PlayerOptionsModel", "Gordon Freeman", "models/Player/cordon_HEV.mdl" )
list.Set( "PlayerOptionsModel", "ODST", "models/voxelzero/player/odst.mdl" )
list.Set( "PlayerOptionsModel", "Atlas", "models/survivors/atlas.mdl" )
list.Set( "PlayerOptionsModel", "HUNK_cvp", "models/player/lordvipes/rerc_hunk/hunk_cvp_fix.mdl" )
list.Set( "PlayerOptionsModel", "NIGHT HAWK_cvp", "models/player/lordvipes/rerc_nighthawk/nighthawk_cvp_fix.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando", "models/player/SGG/Starwars/clone_commando.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando (MP A)", "models/Player/SGG/Starwars/clone_commando_mp_a.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando (MP B)", "models/Player/SGG/Starwars/clone_commando_mp_b.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando (MP C)", "models/Player/SGG/Starwars/clone_commando_mp_c.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando (MP D)", "models/Player/SGG/Starwars/clone_commando_mp_d.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando Boss", "models/Player/SGG/Starwars/clone_commando_38.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando Fixer", "models/Player/SGG/Starwars/clone_commando_40.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando Scorch", "models/player/sgg/starwars/clone_commando_62_fix.mdl" )
list.Set( "PlayerOptionsModel", "Clone Commando Sev", "models/Player/SGG/Starwars/clone_commando_07.mdl" )
list.Set( "PlayerOptionsModel", "Bill", "models/enhanced_survivors/player/player_namvet.mdl" )
list.Set( "PlayerOptionsModel", "Thresh", "models/thresh/thresh_fix.mdl" )
list.Set( "PlayerOptionsModel", "Tron Anon", "models/player/anon/anon.mdl" )
list.Set( "PlayerOptionsModel", "Marine", "models/voxelzero/player/marine.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Chiulin", "models/lizards/lizardmanvd.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Ekinar", "models/lizards/lizardmanekinar.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Garway", "models/lizards/lizardmangarway.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Kazgulam", "models/lizards/lizardmankazgulam.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Keser", "models/lizards/lizardmankeser.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Shaman", "models/lizards/lizardmanshaman.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Verafim", "models/lizards/lizardmanverafim.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Warrior", "models/lizards/lizardmanwarrior.mdl" )
list.Set( "PlayerOptionsModel", "Lizardman Shark", "models/lizards/lizardmanshark.mdl" )
list.Set( "PlayerOptionsModel", "Inferno Armour", "models/Mass Effect 2/player/inferno_armour.mdl")
list.Set( "PlayerOptionsModel", "Inferno Armour Colour", "models/Mass Effect 2/player/inferno_armour_colour.mdl")
list.Set( "PlayerOptionsModel", "halo3elite", "Models/player/halo3elite.mdl" )
list.Set( "PlayerOptionsModel", "Spartan (Halo 3 MP)", "models/player/lordvipes/h3_spartans_mps/h3spartan_mps_cvp.mdl" )
list.Set( "PlayerOptionsModel", "Plague Doktor", "models/Splinks/plague_doktor/Plague_Doktor.mdl" )
list.Set( "PlayerOptionsModel", "Iron Man", "models/Avengers/Iron Man/mark7_player.mdl" )
list.Set( "PlayerOptionsModel", "Iron Patriot", "models/Avengers/Iron Man/patriot_player.mdl" )